#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# MythDeck documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '4.5.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
]

autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 2

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'mythdeck_readme'

# General information about the project.
project = 'MythDeck'
copyright = (
    '2022, Joel Baxter' +
    ' <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0;vertical-align:middle" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>' +
    ' (except for <a href="https://thoseawesomeguys.com/prompts/">button icons</a>)'
)
author = 'Joel Baxter'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including any pre-release tag.
release = '1.0.0'
# And without that tag.
version = release.split('-')[0]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The default language to syntax-highlight literals in.
highlight_language = 'none'

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'

# A string of reStructuredText that will be included at the beginning of
# every source file that is read.
rst_prolog = """
.. role:: strike
  :class: strike

.. |br| raw:: html

  <div style="line-height: 0; padding: 0; margin: 0"></div>

.. |aface| raw:: html

  <img alt="A button" title="A button" src="../_static/icons/SteamDeck_A.png" class="inline-icon"/>

.. |bface| raw:: html

  <img alt="B button" title="B button" src="../_static/icons/SteamDeck_B.png" class="inline-icon"/>

.. |dpaddown| raw:: html

  <img alt="D-Pad down" title="D-Pad down" src="../_static/icons/SteamDeck_Dpad_Down.png" class="inline-icon"/>

.. |dpadleft| raw:: html

  <img alt="D-Pad left" title="D-Pad left" src="../_static/icons/SteamDeck_Dpad_Left.png" class="inline-icon"/>

.. |dpad| raw:: html

  <img alt="D-Pad" title="D-Pad" src="../_static/icons/SteamDeck_Dpad.png" class="inline-icon"/>

.. |dpadright| raw:: html

  <img alt="D-Pad right" title="D-Pad right" src="../_static/icons/SteamDeck_Dpad_Right.png" class="inline-icon"/>

.. |dpadup| raw:: html

  <img alt="D-Pad up" title="D-Pad up" src="../_static/icons/SteamDeck_Dpad_Up.png" class="inline-icon"/>

.. |gyro| raw:: html

  <img alt="gyro" title="gyro" src="../_static/icons/SteamDeck_Gyro.png" class="inline-icon"/>

.. |l1| raw:: html

  <img alt="left bumper" title="left bumper" src="../_static/icons/SteamDeck_L1.png" class="inline-icon"/>

.. |l2| raw:: html

  <img alt="left trigger" title="left trigger" src="../_static/icons/SteamDeck_L2.png" class="inline-icon"/>

.. |l4| raw:: html

  <img alt="left front paddle" title="left front paddle" src="../_static/icons/SteamDeck_L4.png" class="inline-icon"/>

.. |l5| raw:: html

  <img alt="left rear paddle" title="left rear paddle" src="../_static/icons/SteamDeck_L5.png" class="inline-icon"/>

.. |lstickclick| raw:: html

  <img alt="left stick click" title="left stick click" src="../_static/icons/SteamDeck_Left_Stick_Click.png" class="inline-icon"/>

.. |lstick| raw:: html

  <img alt="left stick" title="left stick" src="../_static/icons/SteamDeck_Left_Stick.png" class="inline-icon"/>

.. |ltrack| raw:: html

  <img alt="left trackpad" title="left trackpad" src="../_static/icons/SteamDeck_Left_Track.png" class="inline-icon"/>

.. |menu| raw:: html

  <img alt="menu/start" title="menu/start" src="../_static/icons/SteamDeck_Menu.png" class="inline-icon"/>

.. |r1| raw:: html

  <img alt="right bumper" title="right bumper" src="../_static/icons/SteamDeck_R1.png" class="inline-icon"/>

.. |r2| raw:: html

  <img alt="right trigger" title="right trigger" src="../_static/icons/SteamDeck_R2.png" class="inline-icon"/>

.. |r4| raw:: html

  <img alt="right front paddle" title="right front paddle" src="../_static/icons/SteamDeck_R4.png" class="inline-icon"/>

.. |r5| raw:: html

  <img alt="right rear paddle" title="right rear paddle" src="../_static/icons/SteamDeck_R5.png" class="inline-icon"/>

.. |rstickclick| raw:: html

  <img alt="right stick click" title="right stick click" src="../_static/icons/SteamDeck_Right_Stick_Click.png" class="inline-icon"/>

.. |rstick| raw:: html

  <img alt="right stick" title="right stick" src="../_static/icons/SteamDeck_Right_Stick.png" class="inline-icon"/>

.. |rtrack| raw:: html

  <img alt="right trackpad" title="right trackpad" src="../_static/icons/SteamDeck_Right_Track.png" class="inline-icon"/>

.. |view| raw:: html

  <img alt="view/select button" title="view/select button" src="../_static/icons/SteamDeck_Square.png" class="inline-icon"/>

.. |steam| raw:: html

  <img alt="steam button" title="steam button" src="../_static/icons/SteamDeck_Steam.png" class="inline-icon"/>

.. |xface| raw:: html

  <img alt="X button" title="X button" src="../_static/icons/SteamDeck_X.png" class="inline-icon"/>

.. |yface| raw:: html

  <img alt="Y button" title="Y button" src="../_static/icons/SteamDeck_Y.png" class="inline-icon"/>

.. |plus| raw:: html

  <img alt="+" title="+" src="../_static/icons/combo.png"/ class="inline-icon"/>

.. |lowplus| raw:: html

  <img alt="+" title="+" src="../_static/icons/lowcombo.png"/ class="inline-icon"/>
"""


# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'description': 'Steam Deck setup for Myth 2',
    'extra_nav_links': {},
    'fixed_sidebar': True,
    'page_width': 'auto',
    'show_related': True,
    'github_button': False,
    'show_relbars': True,
    'show_powered_by' : True,
}

# These paths are either relative to html_static_path or fully qualified paths.
#
html_css_files = ['css/text.css', 'css/media.css', 'css/icons.css', 'css/page.css']
html_js_files = ['js/imagetoggle.js']

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
#        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

# If true, the reST sources are included in the HTML build as _sources/name.
#
html_copy_source = False

# If true, links to the reST sources are added to the pages.
#
html_show_sourcelink = False

# If false, no index is generated.
#
html_use_index = False

# If true, the text around the keyword is shown as summary of each search
# result. Note: this only works for online docs apparently, not local
# files.
#
html_show_search_summary = True

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.
#
html_favicon = '_static/favicon.ico'

# Don't link to full-size image from scaled image.
html_scaled_image_link = False